POST http://localhost:3001/exercises
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": "q"
}

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "2023-01-21",
  "ssn":"090471-8898",
  "gender": "male",
  "occupation": "Technician"
}

###
GET http://localhost:3001/api/patients

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


###

POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "date": "2023-01-21",
  "specialist":"MD House",
  "diagnosisCodes": ["J03.0"],
  "type": "Hospital",
  "discharge": {
    "date": "2015-01-16",
    "criteria": "Thumb has healed."
  }
}

###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "date": "2019-08-05",
  "specialist":"MD House",
  "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"],
  "type": "OccupationalHealthcare",
  "sickLeave": {
    "startDate": "2019-08-05",
    "endDate": "2019-08-28"
  }
}

###
POST http://localhost:3001/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "date": "2019-08-05",
  "specialist":"MD House",
  "type": "HealthCheck",
  "healthCheckRating": 2
}